name: "codesigner"
author: "E-Signer.com"
branding:
  icon: "feather"
  color: "green"
description: ""
inputs:
  command:
    description: ""
    required: true
    default: "--version"    
  username:
    description: ""
    required: false
  password:
    description: ""
    required: false
  credential_id:
    description: ""
    required: false
  totp_secret:
    description: ""
    required: false
  program_name:
    description: ""
    required: false
  file_path:
    description: ""
    required: false
  output_path:
    description: ""
    required: false
  malware_block:
    description: ""
    required: false
    default: "false"
  environment_name:
    description: ""
    required: false
    default: "PROD"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
